name: CI

on: push

jobs:
  compile-assets:
    name: Compile assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Build jS
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn
      - name: YARN Build
        run: |
          yarn run prod
          cat public/mix-manifest.json # see version in log
      - name: Upload compile assets
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: public
  test-php:
    name: Test/Lint PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring, bmath
      - name: Composer install
        run: composer install
      - name: Generate artisan key
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Generate passport keys
        run: |
          php artisan passport:keys
      - name: Run tests
        run: ./vendor/bin/phpunit
